import { Banknote, ClipboardPen, Search, Settings2, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';

import { ActionFeedbackDialog, type ActionFeedbackTone } from '../components/feedback/ActionFeedbackDialog';
import { PageShell } from '../components/layout/PageShell';
import { ConfirmDialog } from '../components/ui/Actions';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from '../components/ui/Feedback';
import { SectionCard, SectionHeader } from '../components/ui/Surface';
import { PayrollEstimateView } from '../features/payroll/PayrollEstimateView';
import { formatMoney, todayInChina, type AdminPayrollSummary, type PayrollEstimate } from '../features/payroll/model';
import { useAuth } from '../features/auth/AuthContext';
import { supabase } from '../lib/supabase';
import { addPayrollPenalty, loadAdminPayrollEstimates, loadPayrollAdminSetup, revokePayrollPenalty, savePayrollEmployeeRule, savePayrollPerformanceRule, savePayrollRevenue, type PayrollEmployeeRule, type PayrollPerformanceRule } from '../services/payroll.service';

type Tab = 'overview' | 'employees' | 'performance' | 'revenue' | 'penalties';
type Feedback = { title: string; message: string; tone: ActionFeedbackTone };
const tabs: { key: Tab; label: string }[] = [{ key: 'overview', label: '实时工资' }, { key: 'employees', label: '员工参数' }, { key: 'performance', label: '绩效规则' }, { key: 'revenue', label: '营业收入' }, { key: 'penalties', label: '处罚' }];
const monthStart = (date = todayInChina()) => `${date.slice(0, 7)}-01`;

export function AdminPayrollPage() {
  const [params, setParams] = useSearchParams();
  const tab = (tabs.some((item) => item.key === params.get('tab')) ? params.get('tab') : 'overview') as Tab;
  return <PageShell eyebrow="门店运营系统 · 管理员" title="实时薪资" backTo="/app/menu" contentGapClassName="gap-3">
    <nav className="ui-card grid grid-cols-5 gap-1 p-1.5" aria-label="实时薪资功能">{tabs.map((item) => <button className={`min-h-10 rounded-lg px-1 text-[11px] font-bold ${tab === item.key ? 'bg-brand-700 text-white' : 'text-slate-600'}`} key={item.key} onClick={() => setParams({ tab: item.key })} type="button">{item.label}</button>)}</nav>
    {tab === 'overview' ? <PayrollOverview /> : null}
    {tab === 'employees' ? <EmployeeRules /> : null}
    {tab === 'performance' ? <PerformanceRules /> : null}
    {tab === 'revenue' ? <RevenueManager /> : null}
    {tab === 'penalties' ? <PenaltyManager /> : null}
  </PageShell>;
}

function PayrollOverview() {
  const auth = useAuth();
  const [asOf, setAsOf] = useState(todayInChina());
  const [storeId, setStoreId] = useState('');
  const [search, setSearch] = useState('');
  const [result, setResult] = useState<AdminPayrollSummary | null>(null);
  const [selected, setSelected] = useState<PayrollEstimate | null>(null);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const load = useCallback(async () => { if (!supabase) return; setStatus('loading'); try { setResult(await loadAdminPayrollEstimates(supabase, { asOf, storeId, search })); setStatus('ready'); } catch { setStatus('error'); } }, [asOf, search, storeId]);
  useEffect(() => { const id = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(id); }, [load]);
  if (selected) return <><button className="ui-button-secondary" onClick={() => setSelected(null)} type="button">返回工资列表</button><PayrollEstimateView estimate={selected} /></>;
  return <>
    <SectionCard className="p-3"><div className="grid grid-cols-2 gap-2"><label className="text-xs font-semibold text-slate-600">截止日期<input className="ui-input mt-1" max={todayInChina()} onChange={(event) => setAsOf(event.target.value)} type="date" value={asOf} /></label><label className="text-xs font-semibold text-slate-600">门店范围<select className="ui-input mt-1" onChange={(event) => setStoreId(event.target.value)} value={storeId}><option value="">全部授权门店</option>{auth.availableStores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label></div><label className="relative mt-2 block"><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-slate-400" /><input className="ui-input pl-9" onChange={(event) => setSearch(event.target.value)} placeholder="搜索员工姓名或账号" value={search} /></label></SectionCard>
    {result ? <section className="grid grid-cols-2 gap-2"><SummaryMetric label="预估合计（已知项）" value={formatMoney(result.knownEstimatedTotal)} /><SummaryMetric label="数据完整员工" value={`${result.completeCount}/${result.employeeCount}`} /></section> : null}
    <p className="rounded-lg bg-brand-50 px-3 py-2 text-xs leading-5 text-brand-800">“全部授权门店”会合并同一员工的所有门店数据，同一天跨门店出勤只计 1 天。门店筛选用于查看对应门店员工。</p>
    {status === 'loading' ? <LoadingState label="正在计算实时预估工资" /> : null}{status === 'error' ? <ErrorState message="暂时无法加载实时工资。" onRetry={() => void load()} /> : null}
    {status === 'ready' && !result?.items.length ? <EmptyState title="暂无符合条件的员工" /> : null}
    {status === 'ready' ? <section className="space-y-2">{result?.items.map((item) => <button className="ui-interactive ui-card w-full p-3.5 text-left" key={item.profileId} onClick={() => setSelected(item)} type="button"><div className="flex items-start justify-between gap-3"><div><b>{item.displayName}</b><p className="mt-0.5 text-xs text-slate-500">出勤 {item.attendanceDays} 天 · 迟到 {item.lateCount} 次</p></div><StatusBadge tone={item.dataComplete ? 'success' : 'warning'}>{item.dataComplete ? '数据完整' : '待完善'}</StatusBadge></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="基本工资" value={formatMoney(item.accruedBaseSalary)} /><Mini label="绩效" value={formatMoney(item.accruedPerformance)} /><Mini label="预估可发" value={formatMoney(item.dataComplete ? item.estimatedPayable : item.knownEstimatedPayable)} /></div></button>)}</section> : null}
  </>;
}

function EmployeeRules() {
  const auth = useAuth();
  const [setup, setSetup] = useState<Awaited<ReturnType<typeof loadPayrollAdminSetup>> | null>(null);
  const [profileId, setProfileId] = useState('');
  const [form, setForm] = useState({ base: '', housing: '', performance: '', commission: '', effectiveFrom: todayInChina(), reason: '', housingEnabled: true, performanceEnabled: true, commissionEnabled: false, confirmed: false, storeIds: [] as string[] });
  const [feedback, setFeedback] = useState<Feedback | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!supabase) return; try { const data = await loadPayrollAdminSetup(supabase, monthStart()); setSetup(data); setProfileId((value) => value || data.profiles[0]?.id || ''); } catch (error) { setFeedback({ title: '加载失败', message: error instanceof Error ? error.message : '暂时无法加载。', tone: 'danger' }); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!setup || !profileId) return; const rule = setup.rules.find((item) => item.profile_id === profileId); setForm(ruleToForm(rule, setup.commissionStores.filter((item) => item.rule_id === rule?.id).map((item) => item.store_id))); }, [profileId, setup]);
  const save = async () => { if (!supabase || !profileId) return; if (!form.base || !form.reason.trim()) { setFeedback({ title: '请完善工资参数', message: '月基本工资和本次修改原因不能为空。', tone: 'warning' }); return; } setBusy(true); try { await savePayrollEmployeeRule(supabase, profileId, { monthlyBaseSalary: Number(form.base), monthlyHousingAllowance: Number(form.housing || 0), fullPerformanceAmount: form.performance, commissionRate: form.commission ? Number(form.commission) / 100 : '', housingEnabled: form.housingEnabled, performanceEnabled: form.performanceEnabled, commissionEnabled: form.commissionEnabled, confirmed: form.confirmed, effectiveFrom: form.effectiveFrom, changeReason: form.reason.trim() }, form.storeIds); setFeedback({ title: '员工工资参数已保存', message: '新参数将按所选生效日期参与实时预估，历史规则已保留。', tone: 'success' }); await load(); } catch (error) { setFeedback({ title: '保存未完成', message: error instanceof Error ? error.message : '请稍后重试。', tone: 'danger' }); } finally { setBusy(false); } };
  if (!setup) return <LoadingState label="正在加载员工工资参数" />;
  return <><SectionCard><SectionHeader icon={Settings2} title="员工工资参数" description="调整后按生效日期切换，历史参数不会被覆盖。" /><label className="mt-3 block text-sm font-semibold">选择员工<select className="ui-input mt-1" onChange={(event) => setProfileId(event.target.value)} value={profileId}>{setup.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name} · {profile.username}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-2"><Field label="月基本工资" value={form.base} onChange={(base) => setForm((value) => ({ ...value, base }))} /><Field label="月房补" value={form.housing} onChange={(housing) => setForm((value) => ({ ...value, housing }))} /><Field label="满绩效金额" value={form.performance} onChange={(performance) => setForm((value) => ({ ...value, performance }))} /><Field label="提成比例（%）" value={form.commission} onChange={(commission) => setForm((value) => ({ ...value, commission }))} /></div><div className="mt-3 grid grid-cols-3 gap-2">{([['housingEnabled', '启用房补'], ['performanceEnabled', '启用绩效'], ['commissionEnabled', '启用提成']] as const).map(([key, label]) => <label className="rounded-lg bg-slate-50 p-2 text-xs font-semibold" key={key}><input checked={form[key]} className="mr-1.5" onChange={(event) => setForm((value) => ({ ...value, [key]: event.target.checked }))} type="checkbox" />{label}</label>)}</div>{form.commissionEnabled ? <div className="mt-3"><p className="text-sm font-semibold">提成门店</p><div className="mt-1 grid grid-cols-2 gap-2">{auth.availableStores.map((store) => <label className="rounded-lg border p-2 text-xs" key={store.id}><input checked={form.storeIds.includes(store.id)} className="mr-1.5" onChange={(event) => setForm((value) => ({ ...value, storeIds: event.target.checked ? [...value.storeIds, store.id] : value.storeIds.filter((id) => id !== store.id) }))} type="checkbox" />{store.short_name}</label>)}</div></div> : null}<label className="mt-3 block text-sm font-semibold">生效日期<input className="ui-input mt-1" onChange={(event) => setForm((value) => ({ ...value, effectiveFrom: event.target.value }))} type="date" value={form.effectiveFrom} /></label><label className="mt-3 block text-sm font-semibold">修改原因<input className="ui-input mt-1" onChange={(event) => setForm((value) => ({ ...value, reason: event.target.value }))} placeholder="例如：转正调薪或管理员首次确认" value={form.reason} /></label><label className="mt-3 flex items-center rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-900"><input checked={form.confirmed} className="mr-2" onChange={(event) => setForm((value) => ({ ...value, confirmed: event.target.checked }))} type="checkbox" />我已核对并确认本员工工资参数</label><button className="ui-button-primary mt-3 w-full" disabled={busy} onClick={() => void save()} type="button">{busy ? '正在保存' : '保存员工工资参数'}</button></SectionCard><ActionFeedbackDialog message={feedback?.message ?? ''} onClose={() => setFeedback(null)} open={Boolean(feedback)} title={feedback?.title ?? ''} tone={feedback?.tone} /></>;
}

function PerformanceRules() {
  const [current, setCurrent] = useState<PayrollPerformanceRule | null>(null); const [feedback, setFeedback] = useState<Feedback | null>(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState(defaultPerformanceForm());
  const load = useCallback(async () => { if (!supabase) return; const setup = await loadPayrollAdminSetup(supabase, monthStart()); const rule = setup.performanceRules[0] ?? null; setCurrent(rule); if (rule) setForm(performanceToForm(rule)); }, []);
  useEffect(() => { void load().catch(() => setFeedback({ title: '加载失败', message: '暂时无法加载绩效规则。', tone: 'danger' })); }, [load]);
  const save = async () => { if (!supabase) return; const weight = Number(form.taskWeight) + Number(form.attendanceWeight) + Number(form.disciplineWeight); if (weight !== 100 || !form.reason.trim()) { setFeedback({ title: '请完善绩效规则', message: weight !== 100 ? '任务、考勤和纪律三项权重合计必须等于 100。' : '请填写修改原因。', tone: 'warning' }); return; } setBusy(true); try { await savePayrollPerformanceRule(supabase, { taskWeight: Number(form.taskWeight), attendanceWeight: Number(form.attendanceWeight), disciplineWeight: Number(form.disciplineWeight), lateDeduction1To10: Number(form.late1), lateDeduction11To20: Number(form.late2), lateDeduction21To30: Number(form.late3), lateDeduction31Plus: Number(form.late4), gradeAMin: Number(form.aMin), gradeBMin: Number(form.bMin), gradeCMin: Number(form.cMin), gradeACoefficient: Number(form.aRate) / 100, gradeBCoefficient: Number(form.bRate) / 100, gradeCCoefficient: Number(form.cRate) / 100, gradeDCoefficient: Number(form.dRate) / 100, effectiveFrom: form.effectiveFrom, changeReason: form.reason.trim() }); setFeedback({ title: '绩效规则已保存', message: '新规则将按生效日期用于实时工资计算。', tone: 'success' }); await load(); } catch (error) { setFeedback({ title: '保存未完成', message: error instanceof Error ? error.message : '请稍后重试。', tone: 'danger' }); } finally { setBusy(false); } };
  return <><SectionCard><SectionHeader icon={ShieldCheck} title="绩效评分规则" description={`当前规则：${current?.effective_from ?? '尚未配置'}`} /><h3 className="mt-4 text-sm font-bold">评分权重（合计 100）</h3><div className="mt-2 grid grid-cols-3 gap-2"><Field label="任务" value={form.taskWeight} onChange={(taskWeight) => setForm((v) => ({ ...v, taskWeight }))} /><Field label="考勤" value={form.attendanceWeight} onChange={(attendanceWeight) => setForm((v) => ({ ...v, attendanceWeight }))} /><Field label="纪律" value={form.disciplineWeight} onChange={(disciplineWeight) => setForm((v) => ({ ...v, disciplineWeight }))} /></div><h3 className="mt-4 text-sm font-bold">迟到绩效扣分</h3><div className="mt-2 grid grid-cols-2 gap-2"><Field label="1–10 分钟" value={form.late1} onChange={(late1) => setForm((v) => ({ ...v, late1 }))} /><Field label="11–20 分钟" value={form.late2} onChange={(late2) => setForm((v) => ({ ...v, late2 }))} /><Field label="21–30 分钟" value={form.late3} onChange={(late3) => setForm((v) => ({ ...v, late3 }))} /><Field label="31 分钟以上" value={form.late4} onChange={(late4) => setForm((v) => ({ ...v, late4 }))} /></div><h3 className="mt-4 text-sm font-bold">等级最低分 / 金额系数</h3><div className="mt-2 grid grid-cols-2 gap-2"><Field label="A 最低分" value={form.aMin} onChange={(aMin) => setForm((v) => ({ ...v, aMin }))} /><Field label="A 系数 %" value={form.aRate} onChange={(aRate) => setForm((v) => ({ ...v, aRate }))} /><Field label="B 最低分" value={form.bMin} onChange={(bMin) => setForm((v) => ({ ...v, bMin }))} /><Field label="B 系数 %" value={form.bRate} onChange={(bRate) => setForm((v) => ({ ...v, bRate }))} /><Field label="C 最低分" value={form.cMin} onChange={(cMin) => setForm((v) => ({ ...v, cMin }))} /><Field label="C 系数 %" value={form.cRate} onChange={(cRate) => setForm((v) => ({ ...v, cRate }))} /><Field label="D 系数 %" value={form.dRate} onChange={(dRate) => setForm((v) => ({ ...v, dRate }))} /></div><label className="mt-3 block text-sm font-semibold">生效日期<input className="ui-input mt-1" onChange={(event) => setForm((v) => ({ ...v, effectiveFrom: event.target.value }))} type="date" value={form.effectiveFrom} /></label><label className="mt-3 block text-sm font-semibold">修改原因<input className="ui-input mt-1" onChange={(event) => setForm((v) => ({ ...v, reason: event.target.value }))} value={form.reason} /></label><button className="ui-button-primary mt-3 w-full" disabled={busy} onClick={() => void save()} type="button">保存绩效规则</button></SectionCard><ActionFeedbackDialog message={feedback?.message ?? ''} onClose={() => setFeedback(null)} open={Boolean(feedback)} title={feedback?.title ?? ''} tone={feedback?.tone} /></>;
}

function RevenueManager() {
  const auth = useAuth(); const [setup, setSetup] = useState<Awaited<ReturnType<typeof loadPayrollAdminSetup>> | null>(null); const [storeId, setStoreId] = useState(auth.availableStores[0]?.id ?? ''); const [date, setDate] = useState(todayInChina()); const [amount, setAmount] = useState(''); const [note, setNote] = useState(''); const [feedback, setFeedback] = useState<Feedback | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (supabase) setSetup(await loadPayrollAdminSetup(supabase, monthStart(date))); }, [date]); useEffect(() => { void load().catch(() => undefined); }, [load]);
  const save = async () => { if (!supabase || !auth.profile || !storeId || amount === '') { setFeedback({ title: '请完善营业收入', message: '请选择门店并填写已确认的当日营业收入。', tone: 'warning' }); return; } setBusy(true); try { await savePayrollRevenue(supabase, { store_id: storeId, revenue_date: date, confirmed_amount: Number(amount), note: note.trim(), updated_by: auth.profile.id }); setFeedback({ title: '营业收入已保存', message: '该金额已纳入员工截至当前日期的提成预估。', tone: 'success' }); setAmount(''); setNote(''); await load(); } catch (error) { setFeedback({ title: '保存未完成', message: error instanceof Error ? error.message : '请稍后重试。', tone: 'danger' }); } finally { setBusy(false); } };
  return <><SectionCard><SectionHeader icon={Banknote} title="每日已确认营业收入" description="提成按本月 1 日至截止日期的每日金额累计，不预测月末。" /><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-sm font-semibold">门店<select className="ui-input mt-1" onChange={(event) => setStoreId(event.target.value)} value={storeId}>{auth.availableStores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label className="text-sm font-semibold">日期<input className="ui-input mt-1" max={todayInChina()} onChange={(event) => setDate(event.target.value)} type="date" value={date} /></label></div><Field label="确认金额" value={amount} onChange={setAmount} /><label className="mt-3 block text-sm font-semibold">备注<input className="ui-input mt-1" onChange={(event) => setNote(event.target.value)} value={note} /></label><button className="ui-button-primary mt-3 w-full" disabled={busy} onClick={() => void save()} type="button">保存营业收入</button></SectionCard><section className="space-y-2">{setup?.revenues.slice(0, 30).map((row) => <SectionCard className="p-3" key={row.id}><div className="flex justify-between gap-3"><span><b>{auth.availableStores.find((store) => store.id === row.store_id)?.short_name ?? '门店'}</b><small className="block text-slate-500">{row.revenue_date}</small></span><b>{formatMoney(row.confirmed_amount)}</b></div></SectionCard>)}</section><ActionFeedbackDialog message={feedback?.message ?? ''} onClose={() => setFeedback(null)} open={Boolean(feedback)} title={feedback?.title ?? ''} tone={feedback?.tone} /></>;
}

function PenaltyManager() {
  const auth = useAuth(); const [setup, setSetup] = useState<Awaited<ReturnType<typeof loadPayrollAdminSetup>> | null>(null); const [profileId, setProfileId] = useState(''); const [date, setDate] = useState(todayInChina()); const [reason, setReason] = useState(''); const [amount, setAmount] = useState('0'); const [deduction, setDeduction] = useState('0'); const [level, setLevel] = useState<'reminder' | 'warning' | 'formal_warning' | 'serious'>('warning'); const [feedback, setFeedback] = useState<Feedback | null>(null); const [revokeId, setRevokeId] = useState(''); const [revokeReason, setRevokeReason] = useState('');
  const load = useCallback(async () => { if (!supabase) return; const data = await loadPayrollAdminSetup(supabase, monthStart(date)); setSetup(data); setProfileId((value) => value || data.profiles[0]?.id || ''); }, [date]); useEffect(() => { void load().catch(() => undefined); }, [load]);
  const save = async () => { if (!supabase || !auth.profile || !profileId || !reason.trim()) { setFeedback({ title: '请完善处罚信息', message: '员工、日期和处罚原因不能为空。', tone: 'warning' }); return; } try { await addPayrollPenalty(supabase, { profile_id: profileId, event_date: date, reason: reason.trim(), amount: Number(amount), event_level: level, performance_deduction: Number(deduction), created_by: auth.profile.id }); setFeedback({ title: '处罚记录已保存', message: '罚款金额与绩效扣分已分别计入实时预估。', tone: 'success' }); setReason(''); await load(); } catch (error) { setFeedback({ title: '保存未完成', message: error instanceof Error ? error.message : '请稍后重试。', tone: 'danger' }); } };
  const revoke = async () => { if (!supabase || !revokeId || !revokeReason.trim()) { setFeedback({ title: '请填写撤销原因', message: '撤销处罚必须保留原因。', tone: 'warning' }); return; } const id = revokeId; setRevokeId(''); try { await revokePayrollPenalty(supabase, id, revokeReason.trim()); setFeedback({ title: '处罚记录已撤销', message: '该记录不再参与工资和绩效计算。', tone: 'success' }); setRevokeReason(''); await load(); } catch (error) { setFeedback({ title: '撤销未完成', message: error instanceof Error ? error.message : '请稍后重试。', tone: 'danger' }); } };
  return <><SectionCard><SectionHeader icon={ClipboardPen} title="其他罚款与纪律记录" description="金额与绩效扣分分别填写，系统不会根据金额猜测扣分。" /><label className="mt-3 block text-sm font-semibold">员工<select className="ui-input mt-1" onChange={(event) => setProfileId(event.target.value)} value={profileId}>{setup?.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-sm font-semibold">日期<input className="ui-input mt-1" max={todayInChina()} onChange={(event) => setDate(event.target.value)} type="date" value={date} /></label><label className="text-sm font-semibold">事件等级<select className="ui-input mt-1" onChange={(event) => setLevel(event.target.value as typeof level)} value={level}><option value="reminder">提醒</option><option value="warning">警告</option><option value="formal_warning">正式警告</option><option value="serious">严重违纪</option></select></label><Field label="罚款金额" value={amount} onChange={setAmount} /><Field label="绩效扣分" value={deduction} onChange={setDeduction} /></div><label className="mt-3 block text-sm font-semibold">原因<input className="ui-input mt-1" onChange={(event) => setReason(event.target.value)} value={reason} /></label><button className="ui-button-primary mt-3 w-full" onClick={() => void save()} type="button">保存处罚记录</button></SectionCard><section className="space-y-2">{setup?.penalties.map((row) => <SectionCard className="p-3" key={row.id}><div className="flex items-start justify-between gap-3"><span><b>{setup.profiles.find((profile) => profile.id === row.profile_id)?.display_name}</b><small className="block text-slate-500">{row.event_date} · {row.reason}</small></span><StatusBadge tone={row.status === 'active' ? 'danger' : 'info'}>{row.status === 'active' ? `-${formatMoney(row.amount)}` : '已撤销'}</StatusBadge></div>{row.status === 'active' ? <button className="ui-button-secondary mt-2 min-h-9 w-full text-xs" onClick={() => setRevokeId(row.id)} type="button">撤销此记录</button> : null}</SectionCard>)}</section><ConfirmDialog confirmLabel="确认撤销" onCancel={() => setRevokeId('')} onConfirm={() => void revoke()} open={Boolean(revokeId)} title="撤销处罚记录"><label className="block text-sm font-semibold">撤销原因<input className="ui-input mt-1" onChange={(event) => setRevokeReason(event.target.value)} value={revokeReason} /></label></ConfirmDialog><ActionFeedbackDialog message={feedback?.message ?? ''} onClose={() => setFeedback(null)} open={Boolean(feedback)} title={feedback?.title ?? ''} tone={feedback?.tone} /></>;
}

function Field({ label, onChange, value }: { label: string; onChange: (value: string) => void; value: string }) { return <label className="mt-3 block text-sm font-semibold">{label}<input className="ui-input mt-1" min="0" onChange={(event) => onChange(event.target.value)} step="0.01" type="number" value={value} /></label>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2"><b className="block truncate text-xs tabular-nums">{value}</b><span className="text-[10px] text-slate-500">{label}</span></div>; }
function SummaryMetric({ label, value }: { label: string; value: string }) { return <SectionCard className="p-3"><b className="block text-lg tabular-nums text-slate-900">{value}</b><span className="text-xs text-slate-500">{label}</span></SectionCard>; }
function ruleToForm(rule: PayrollEmployeeRule | undefined, storeIds: string[]) { return { base: rule ? String(rule.monthly_base_salary) : '', housing: rule ? String(rule.monthly_housing_allowance) : '', performance: rule?.full_performance_amount == null ? '' : String(rule.full_performance_amount), commission: rule?.commission_rate == null ? '' : String(rule.commission_rate * 100), effectiveFrom: rule?.effective_from ?? todayInChina(), reason: '', housingEnabled: rule?.housing_enabled ?? true, performanceEnabled: rule?.performance_enabled ?? true, commissionEnabled: rule?.commission_enabled ?? false, confirmed: rule?.confirmed ?? false, storeIds }; }
function defaultPerformanceForm() { return { taskWeight: '60', attendanceWeight: '25', disciplineWeight: '15', late1: '1', late2: '3', late3: '5', late4: '10', aMin: '90', bMin: '80', cMin: '70', aRate: '100', bRate: '80', cRate: '50', dRate: '20', effectiveFrom: todayInChina(), reason: '' }; }
function performanceToForm(rule: PayrollPerformanceRule) { return { taskWeight: String(rule.task_weight), attendanceWeight: String(rule.attendance_weight), disciplineWeight: String(rule.discipline_weight), late1: String(rule.late_deduction_1_10), late2: String(rule.late_deduction_11_20), late3: String(rule.late_deduction_21_30), late4: String(rule.late_deduction_31_plus), aMin: String(rule.grade_a_min), bMin: String(rule.grade_b_min), cMin: String(rule.grade_c_min), aRate: String(rule.grade_a_coefficient * 100), bRate: String(rule.grade_b_coefficient * 100), cRate: String(rule.grade_c_coefficient * 100), dRate: String(rule.grade_d_coefficient * 100), effectiveFrom: rule.effective_from, reason: '' }; }
